CREATE TABLE IF NOT EXISTS flow_definition (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  flow_code VARCHAR(64) NOT NULL,
  platform_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_flow_code (flow_code)
);

CREATE TABLE IF NOT EXISTS run_record (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  run_id VARCHAR(128) NOT NULL,
  flow_code VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  message VARCHAR(512) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_run_id (run_id)
);
